name: run-data-pipeline

on:
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install-python-deps
        run: pip install -r requirements.txt
      - name: ingest
        run: python etl_runners/etl_run_arxiv.py
      - name: transform
        run: echo "Nothing to do... yet!"
      - name: commit
          run: |
            git add db/db.sqlite db/raw.sqlite
            git commit -m 'Update SQLite DB' || echo "No changes to commit"
            git push origin || echo "No changes to commit"